on: [push, pull_request,repository_dispatch,workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  nodejs:
    if: github.ref == 'refs/heads/stable'
    name: NodeJS
    runs-on: macos-latest
    env:
      GEN: ninja

    steps:
      - name: Install Ninja
        run: brew install ninja

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install required node packages
        run: |
          sudo npm i duckdb@1.2.1
          sudo npm install -g  apache-arrow mocha
          sudo npm install  apache-arrow mocha
          npm -v
          node -v

      - name: Build duckdb
        run: |
          cd duckdb
          git checkout 8e52ec43959ab363643d63cb78ee214577111da4 #v1.2.1
          cd ..
          make

      - name: Run JS tests
        run: |
          make test_release_js
