on: [push, pull_request,repository_dispatch]

defaults:
  run:
    shell: bash

jobs:
  python:
    name: Python
    runs-on: macos-latest
    env:
      GEN: ninja

    steps:
    - name: Install Ninja
      run: brew install ninja

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Checkout DuckDB Python
      uses: actions/checkout@v4
      with:
        repository: duckdb/duckdb-python
        path: duckdb-python
        fetch-depth: 0
        submodules: true

    - name: Checkout DuckDB
      shell: bash
      run: |
        cd duckdb
        git fetch origin
        git checkout main
        cd ../duckdb-python/external/duckdb
        git fetch origin
        git checkout main

    - name: Build DuckDB (Python)
      run: |
        cd duckdb-python
        python3 -m pip install .

    - name: Build Arrow Extension
      run: make release

    - name: Install Python Dependencies
      shell: bash
      run: |
        pip install -r test/python/requirements-dev.txt

    - name: Test Python
      run: |
        (cd test/python && python -m pytest)
